# Generated by Django 4.1.3 on 2022-11-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_rename_main_maincategory_kind_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maincategory",
            old_name="kind",
            new_name="main",
        ),
    ]
