# Generated by Django 4.1.3 on 2022-11-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0008_alter_subcategory_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="kind",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
