# Generated by Django 4.1.3 on 2022-11-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_rename_kind_maincategory_main_and_more"),
        ("names", "0003_alter_name_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="main",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.subcategory",
            ),
        ),
    ]
