# Generated by Django 4.1.3 on 2022-11-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0007_rename_main_maincategory_title_and_more"),
        ("names", "0005_alter_name_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="names",
                to="categories.subcategory",
            ),
        ),
    ]
